### ISSUE TITLE
Provide a way for users to change the default output

### ISSUE THREAD

**Issue by guslipkin** [guslipkin/packagePresenter#14]
This will come in the form of the `_pkgslides.yml` file. A general outline and description of options is below. Not all of these options will be implemented at the same time. Further below, a list will outline which options are available until all are available and this issue is closed.

```yml
format:
  theme: default
  functions:
    parameters: {true, false}
    examples: {true, false}
    code: {true, false}
    tests: {true, false}
  datasets:
    format: {true, false}
    source: {true, false}
    references: {true, false}
    # view: {true, false} currently unsupported

functions:
  - file: source1.R # will only include functions in slides
    slides:
      - function1
      - function2
  - file: source2.R # will include all functions
  - file: source3.R
    slides: auto

datasets:
  - dataset1
  - dataset2

---

# Other options

format:
  # lack of `functions:`
# Excluding the `functions:` section is the same as setting all slides to 'true'. This will show all slides for which content exists.

format:
  theme: {default, ...}
# see https://quarto.org/docs/presentations/revealjs/themes.html#using-themes
# this is passed directly to the quarto document

functions: {auto, exported, all, none}
# 'auto' uses exported functions and internal functions in the same file as an exported function
# 'exported' uses only exported functions
# 'all' The default behavior, but should be there if the yml file exists

datasets: {all, none}
# 'all' The default behavior, but should be there if the yml file exists
# 'none' No datasets will be included
```

- [x] slides: auto
- [x] slides: exported
- [x] slides: all
- [x] slides: custom
- [x] functions: parameters
- [x] functions: examples
- [x] functions: code
- [ ] functions: tests
- [x] theme
- [x] datasets: all
- [x] datasets: none
- [x] datasets: custom
- [ ] datasets: view option
